version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: delfosti
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432